<?php

namespace EntityProxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Asignacion extends \Entity\Asignacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setReservacionId($reservacionId)
    {
        $this->__load();
        return parent::setReservacionId($reservacionId);
    }

    public function getReservacionId()
    {
        $this->__load();
        return parent::getReservacionId();
    }

    public function setEquipoId($equipoId)
    {
        $this->__load();
        return parent::setEquipoId($equipoId);
    }

    public function getEquipoId()
    {
        $this->__load();
        return parent::getEquipoId();
    }

    public function setSocioId($socioId)
    {
        $this->__load();
        return parent::setSocioId($socioId);
    }

    public function getSocioId()
    {
        $this->__load();
        return parent::getSocioId();
    }

    public function setCadiId($cadiId)
    {
        $this->__load();
        return parent::setCadiId($cadiId);
    }

    public function getCadiId()
    {
        $this->__load();
        return parent::getCadiId();
    }

    public function setHoyo($hoyo)
    {
        $this->__load();
        return parent::setHoyo($hoyo);
    }

    public function getHoyo()
    {
        $this->__load();
        return parent::getHoyo();
    }

    public function setFechaAsignada($fechaAsignada)
    {
        $this->__load();
        return parent::setFechaAsignada($fechaAsignada);
    }

    public function getFechaAsignada()
    {
        $this->__load();
        return parent::getFechaAsignada();
    }

    public function setFechaInicio($fechaInicio)
    {
        $this->__load();
        return parent::setFechaInicio($fechaInicio);
    }

    public function getFechaInicio()
    {
        $this->__load();
        return parent::getFechaInicio();
    }

    public function setFechaFin($fechaFin)
    {
        $this->__load();
        return parent::setFechaFin($fechaFin);
    }

    public function getFechaFin()
    {
        $this->__load();
        return parent::getFechaFin();
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function setEditadoPor($editadoPor)
    {
        $this->__load();
        return parent::setEditadoPor($editadoPor);
    }

    public function getEditadoPor()
    {
        $this->__load();
        return parent::getEditadoPor();
    }

    public function setCreatedate($createdate)
    {
        $this->__load();
        return parent::setCreatedate($createdate);
    }

    public function getCreatedate()
    {
        $this->__load();
        return parent::getCreatedate();
    }

    public function setUpdatedate($updatedate)
    {
        $this->__load();
        return parent::setUpdatedate($updatedate);
    }

    public function getUpdatedate()
    {
        $this->__load();
        return parent::getUpdatedate();
    }

    public function setReservacion(\Entity\Reservacion $reservacion)
    {
        $this->__load();
        return parent::setReservacion($reservacion);
    }

    public function getReservacion()
    {
        $this->__load();
        return parent::getReservacion();
    }

    public function setEquipo(\Entity\Equipo $equipo)
    {
        $this->__load();
        return parent::setEquipo($equipo);
    }

    public function getEquipo()
    {
        $this->__load();
        return parent::getEquipo();
    }

    public function setSocio(\Entity\Socio $socio)
    {
        $this->__load();
        return parent::setSocio($socio);
    }

    public function getSocio()
    {
        $this->__load();
        return parent::getSocio();
    }

    public function setCadi(\Entity\Cadi $cadi = NULL)
    {
        $this->__load();
        return parent::setCadi($cadi);
    }

    public function getCadi()
    {
        $this->__load();
        return parent::getCadi();
    }

    public function addInvitado(\Entity\Invitado $invitados)
    {
        $this->__load();
        return parent::addInvitado($invitados);
    }

    public function removeInvitado(\Entity\Invitado $invitados)
    {
        $this->__load();
        return parent::removeInvitado($invitados);
    }

    public function getInvitados()
    {
        $this->__load();
        return parent::getInvitados();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function toArrayMin()
    {
        $this->__load();
        return parent::toArrayMin();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'reservacion_id', 'equipo_id', 'socio_id', 'cadi_id', 'hoyo', 'fecha_asignada', 'fecha_inicio', 'fecha_fin', 'estatus', 'editado_por', 'createdate', 'updatedate', 'reservacion', 'equipo', 'socio', 'cadi', 'invitados');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}