<?php

namespace EntityProxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Socio extends \Entity\Socio implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setUserId($userId)
    {
        $this->__load();
        return parent::setUserId($userId);
    }

    public function getUserId()
    {
        $this->__load();
        return parent::getUserId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setCedula($cedula)
    {
        $this->__load();
        return parent::setCedula($cedula);
    }

    public function getCedula()
    {
        $this->__load();
        return parent::getCedula();
    }

    public function setNumeroSocio($numeroSocio)
    {
        $this->__load();
        return parent::setNumeroSocio($numeroSocio);
    }

    public function getNumeroSocio()
    {
        $this->__load();
        return parent::getNumeroSocio();
    }

    public function setHandicap($handicap)
    {
        $this->__load();
        return parent::setHandicap($handicap);
    }

    public function getHandicap()
    {
        $this->__load();
        return parent::getHandicap();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setCreatedate($createdate)
    {
        $this->__load();
        return parent::setCreatedate($createdate);
    }

    public function getCreatedate()
    {
        $this->__load();
        return parent::getCreatedate();
    }

    public function setUpdatedate($updatedate)
    {
        $this->__load();
        return parent::setUpdatedate($updatedate);
    }

    public function getUpdatedate()
    {
        $this->__load();
        return parent::getUpdatedate();
    }

    public function addAsignacion(\Entity\Asignacion $asignacions)
    {
        $this->__load();
        return parent::addAsignacion($asignacions);
    }

    public function removeAsignacion(\Entity\Asignacion $asignacions)
    {
        $this->__load();
        return parent::removeAsignacion($asignacions);
    }

    public function getAsignacions()
    {
        $this->__load();
        return parent::getAsignacions();
    }

    public function addEquipo(\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::addEquipo($equipos);
    }

    public function removeEquipo(\Entity\Equipo $equipos)
    {
        $this->__load();
        return parent::removeEquipo($equipos);
    }

    public function getEquipos()
    {
        $this->__load();
        return parent::getEquipos();
    }

    public function addIntegrante(\Entity\Integrante $integrantes)
    {
        $this->__load();
        return parent::addIntegrante($integrantes);
    }

    public function removeIntegrante(\Entity\Integrante $integrantes)
    {
        $this->__load();
        return parent::removeIntegrante($integrantes);
    }

    public function getIntegrantes()
    {
        $this->__load();
        return parent::getIntegrantes();
    }

    public function addReservacion(\Entity\Reservacion $reservacions)
    {
        $this->__load();
        return parent::addReservacion($reservacions);
    }

    public function removeReservacion(\Entity\Reservacion $reservacions)
    {
        $this->__load();
        return parent::removeReservacion($reservacions);
    }

    public function getReservacions()
    {
        $this->__load();
        return parent::getReservacions();
    }

    public function setUser(\Entity\User $user)
    {
        $this->__load();
        return parent::setUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function toArrayMin()
    {
        $this->__load();
        return parent::toArrayMin();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'user_id', 'nombre', 'cedula', 'numero_socio', 'handicap', 'telefono', 'createdate', 'updatedate', 'asignacions', 'equipos', 'integrantes', 'reservacions', 'user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}