<?php

namespace EntityProxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Equipo extends \Entity\Equipo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSocioId($socioId)
    {
        $this->__load();
        return parent::setSocioId($socioId);
    }

    public function getSocioId()
    {
        $this->__load();
        return parent::getSocioId();
    }

    public function setHandicapPromedio($handicapPromedio)
    {
        $this->__load();
        return parent::setHandicapPromedio($handicapPromedio);
    }

    public function getHandicapPromedio()
    {
        $this->__load();
        return parent::getHandicapPromedio();
    }

    public function setCreatedate($createdate)
    {
        $this->__load();
        return parent::setCreatedate($createdate);
    }

    public function getCreatedate()
    {
        $this->__load();
        return parent::getCreatedate();
    }

    public function setUpdatedate($updatedate)
    {
        $this->__load();
        return parent::setUpdatedate($updatedate);
    }

    public function getUpdatedate()
    {
        $this->__load();
        return parent::getUpdatedate();
    }

    public function addAsignacion(\Entity\Asignacion $asignacions)
    {
        $this->__load();
        return parent::addAsignacion($asignacions);
    }

    public function removeAsignacion(\Entity\Asignacion $asignacions)
    {
        $this->__load();
        return parent::removeAsignacion($asignacions);
    }

    public function getAsignacions()
    {
        $this->__load();
        return parent::getAsignacions();
    }

    public function addIntegrante(\Entity\Integrante $integrantes)
    {
        $this->__load();
        return parent::addIntegrante($integrantes);
    }

    public function removeIntegrante(\Entity\Integrante $integrantes)
    {
        $this->__load();
        return parent::removeIntegrante($integrantes);
    }

    public function getIntegrantes()
    {
        $this->__load();
        return parent::getIntegrantes();
    }

    public function addReservacion(\Entity\Reservacion $reservacions)
    {
        $this->__load();
        return parent::addReservacion($reservacions);
    }

    public function removeReservacion(\Entity\Reservacion $reservacions)
    {
        $this->__load();
        return parent::removeReservacion($reservacions);
    }

    public function getReservacions()
    {
        $this->__load();
        return parent::getReservacions();
    }

    public function setSocio(\Entity\Socio $socio)
    {
        $this->__load();
        return parent::setSocio($socio);
    }

    public function getSocio()
    {
        $this->__load();
        return parent::getSocio();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'socio_id', 'handicap_promedio', 'createdate', 'updatedate', 'asignacions', 'integrantes', 'reservacions', 'socio');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}