<?php

namespace EntityProxy\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Reservacion extends \Entity\Reservacion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setSocioId($socioId)
    {
        $this->__load();
        return parent::setSocioId($socioId);
    }

    public function getSocioId()
    {
        $this->__load();
        return parent::getSocioId();
    }

    public function setEquipoId($equipoId)
    {
        $this->__load();
        return parent::setEquipoId($equipoId);
    }

    public function getEquipoId()
    {
        $this->__load();
        return parent::getEquipoId();
    }

    public function setFechaSolicitada($fechaSolicitada)
    {
        $this->__load();
        return parent::setFechaSolicitada($fechaSolicitada);
    }

    public function getFechaSolicitada()
    {
        $this->__load();
        return parent::getFechaSolicitada();
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function setEditadoPor($editadoPor)
    {
        $this->__load();
        return parent::setEditadoPor($editadoPor);
    }

    public function getEditadoPor()
    {
        $this->__load();
        return parent::getEditadoPor();
    }

    public function setCreatedate($createdate)
    {
        $this->__load();
        return parent::setCreatedate($createdate);
    }

    public function getCreatedate()
    {
        $this->__load();
        return parent::getCreatedate();
    }

    public function setUpdatedate($updatedate)
    {
        $this->__load();
        return parent::setUpdatedate($updatedate);
    }

    public function getUpdatedate()
    {
        $this->__load();
        return parent::getUpdatedate();
    }

    public function setAsignacion(\Entity\Asignacion $asignacion)
    {
        $this->__load();
        return parent::setAsignacion($asignacion);
    }

    public function getAsignacion()
    {
        $this->__load();
        return parent::getAsignacion();
    }

    public function addTicket(\Entity\Ticket $tickets)
    {
        $this->__load();
        return parent::addTicket($tickets);
    }

    public function removeTicket(\Entity\Ticket $tickets)
    {
        $this->__load();
        return parent::removeTicket($tickets);
    }

    public function getTickets()
    {
        $this->__load();
        return parent::getTickets();
    }

    public function setSocio(\Entity\Socio $socio)
    {
        $this->__load();
        return parent::setSocio($socio);
    }

    public function getSocio()
    {
        $this->__load();
        return parent::getSocio();
    }

    public function setEquipo(\Entity\Equipo $equipo)
    {
        $this->__load();
        return parent::setEquipo($equipo);
    }

    public function getEquipo()
    {
        $this->__load();
        return parent::getEquipo();
    }

<<<<<<< HEAD
    public function toArrayMin()
    {
        $this->__load();
        return parent::toArrayMin();
    }

    public function toArrayParaAsignacion()
    {
        $this->__load();
        return parent::toArrayParaAsignacion();
    }

=======
>>>>>>> 057ce9b36b279c8ce7d90f557eda41692f315b5f

    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'socio_id', 'equipo_id', 'fecha_solicitada', 'estatus', 'editado_por', 'createdate', 'updatedate', 'asignacion', 'tickets', 'socio', 'equipo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}